// Copyright 2026 Mist Tecnologia LTDA. All rights reserved.

//! Configures the crate for the lwIP options it is built against.
//!
//! The firmware build compiles `../cmake/lwip_rust_config.c` to assembly with the C
//! stack's own flags and passes it in `LWIP_RUST_CONFIG`. Each `@@lwip NAME VALUE` line
//! there becomes a constant in `config.rs`, a `cfg` named `name` in lower case when
//! `NAME` is a feature switch and its value is not 0, and, for the layout entries, a
//! compile-time check of the matching `#[repr(C)]` mirror (the `lwip_layout` cfg).
//!
//! Without `LWIP_RUST_CONFIG`, as in host tests, the options are ESP-IDF v6.1's defaults
//! below, and no layout is checked: host pointers are wider than the target's.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

/// Feature switches: each becomes a `cfg` when not 0. ESP-IDF v6.1 defaults.
const SWITCHES: &[(&str, u64)] = &[
    ("LWIP_IPV4", 1),
    ("LWIP_IPV6", 1),
    ("LWIP_IPV6_SCOPES", 1),
    ("LWIP_IPV6_ADDRESS_LIFETIMES", 1),
    ("LWIP_ND6_ALLOW_RA_UPDATES", 1),
    ("LWIP_SINGLE_NETIF", 0),
    ("LWIP_NETIF_STATUS_CALLBACK", 0),
    ("LWIP_NETIF_LINK_CALLBACK", 0),
    ("LWIP_NETIF_REMOVE_CALLBACK", 0),
    ("LWIP_NETIF_HOSTNAME", 1),
    ("LWIP_CHECKSUM_CTRL_PER_NETIF", 0),
    ("LWIP_NOASSERT", 0),
    ("LWIP_ASSERT_SILENT", 0),
    ("LWIP_HTONS_FN", 1),
    ("LWIP_HTONL_FN", 1),
    ("LWIP_STRNSTR_FN", 1),
    ("LWIP_STRNISTR_FN", 1),
    ("LWIP_STRICMP_FN", 1),
    ("LWIP_STRNICMP_FN", 1),
    ("LWIP_ITOA_FN", 1),
    ("LWIP_NO_CTYPE_H", 0),
    ("LWIP_STANDARD_CHKSUM", 1),
];

/// Values. ESP-IDF v6.1 defaults.
const VALUES: &[(&str, u64)] = &[
    ("LWIP_IPV6_NUM_ADDRESSES", 3),
    ("LWIP_NETIF_CLIENT_DATA", 4),
    ("NETIF_MAX_HWADDR_LEN", 6),
    ("IP4ADDR_STRLEN_MAX", 16),
    ("LWIP_CHKSUM_ALGORITHM", 2),
    ("LWIP_CHKSUM_COPY_ALGORITHM", 0),
];

fn main() {
    println!("cargo::rerun-if-env-changed=LWIP_RUST_CONFIG");
    println!("cargo::rustc-check-cfg=cfg(lwip_layout)");
    for (name, _) in SWITCHES {
        println!("cargo::rustc-check-cfg=cfg({})", name.to_lowercase());
    }

    let mut entries: Vec<(String, u64)> = SWITCHES
        .iter()
        .chain(VALUES)
        .map(|&(name, value)| (name.to_string(), value))
        .collect();
    if let Some(path) = env::var_os("LWIP_RUST_CONFIG") {
        println!("cargo::rerun-if-changed={}", PathBuf::from(&path).display());
        let text = fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("reading {}: {error}", path.display()));
        let generated = parse(&text);
        assert!(
            !generated.is_empty(),
            "{} has no @@lwip entries",
            path.display()
        );
        // A switch or value the configuration does not list (an IPv6 option with IPv6
        // off) is 0; everything it lists replaces the default, and the layout entries are
        // added.
        for (name, value) in &mut entries {
            *value = generated
                .iter()
                .find(|(n, _)| n == name)
                .map_or(0, |&(_, v)| v);
        }
        for (name, value) in generated {
            if !entries.iter().any(|(n, _)| *n == name) {
                entries.push((name, value));
            }
        }
        println!("cargo::rustc-cfg=lwip_layout");
    }

    let value = |name: &str| entries.iter().find(|(n, _)| n == name).map(|&(_, v)| v);
    // inet_chksum.rs translates algorithm 2, the default, which ESP-IDF uses.
    if value("LWIP_STANDARD_CHKSUM") == Some(1) {
        assert_eq!(
            value("LWIP_CHKSUM_ALGORITHM"),
            Some(2),
            "only LWIP_CHKSUM_ALGORITHM 2 is ported"
        );
    }
    assert_eq!(
        value("LWIP_CHKSUM_COPY_ALGORITHM"),
        Some(0),
        "LWIP_CHKSUM_COPY is not ported"
    );

    let mut out = String::from("// Generated by build.rs from the lwIP configuration.\n");
    for (name, value) in &entries {
        writeln!(out, "pub const {name}: usize = {value};").unwrap();
        if value != &0 && SWITCHES.iter().any(|(n, _)| n == name) {
            println!("cargo::rustc-cfg={}", name.to_lowercase());
        }
    }
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("config.rs"), out).expect("writing config.rs");
}

/// The `@@lwip NAME VALUE` entries in `text`.
fn parse(text: &str) -> Vec<(String, u64)> {
    text.lines()
        .filter_map(|line| {
            let rest = &line[line.find("@@lwip ")? + "@@lwip ".len()..];
            let mut words = rest.split(|c: char| c.is_whitespace() || c == '\\' || c == '"');
            let name = words.next()?;
            let value = words.next()?.parse().ok()?;
            Some((name.to_string(), value))
        })
        .collect()
}
